select * from Customers;
select distinct country from Customers;
select * from Customers where CustomerID like 'bl%';
select * from Orders limit 100;
select * from Customers where PostalCode=1010 or postalcode=3012 or postalcode=12209 or postalcode=05023;
select * from Orders where  ShipRegion is not Null;
select * from Customers order by country, city;
insert into Customers values('MACHO','Slim Jim','Randy Savage', 'Macho Man', '123 Ringside Ln', 'Hollywood', 'CA', 90027, 'USA', null, null);
update orders set shipregion='EuroZone' where shipcountry='France';
delete from northwind.`order details` where quantity=1;
select avg(quantity), min(quantity), max(quantity) from northwind.`order details`;
select avg(quantity), min(quantity), max(quantity) from northwind.`order details` group by orderid;
select customerID from orders where orderID=10290;
select orders.CustomerID, orders.orderid, `order details`.unitprice from orders inner join `order details` on orders.orderid=`order details`.OrderID;
select CompanyName, City, Country from customers left join orders on customers.CustomerID=orders.CustomerID;
select shipname, shippeddate, shipcity, ShipCountry from orders right join customers on customers.CustomerID=orders.CustomerID;
select firstname from employees where ReportsTo=2;
select firstname from employees where ReportsTo is null;
select * from customers;
select customerID, CompanyName, ContactTitle from customers where city='london' or city='london';
select distinct city from customers where city is not null;
select firstname from employees order by firstname asc;
select avg(salary) from employees;
select firstname, lastname, max(salary) from employees;
select * from employees where notes like '% BA %' ;
select orderID, UnitPrice, quantity, (unitprice*quantity) as total_price from `order details`;
select * from employees where HireDate between '1994-01-01' and '2021-12-10';
select EmployeeID, LastName, FirstName, hiredate, (year(current_date()) - year(hiredate)) as work_duration from employees;
select productName, UnitsInStock from products order by unitsinstock;
select productName, UnitsInStock from products where UnitsInStock<6 order by unitsinstock;
select* from products where Discontinued is true; -- can also do something where discontinued = 1, but this acts as a bit/bool.
select *, max(unitprice) as highest_price from products;
select * from employees where HireDate>= '1993/1/1';
select * from employees where TitleOfCourtesy= 'mrs.' or titleofcourtesy= 'ms.';
select * from employees where HomePhone like '(206)%';